packages:
  - apps/*

autoInstallPeers: false

overrides:
  postcss: 8.5.25
  sharp: 0.35.0
  undici: 7.29.0

patchedDependencies:
  sharp@0.35.0: patches/sharp@0.35.0.patch

allowBuilds:
  '@alicloud/openapi-core': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
