import 'dotenv/config'

process.env.ALLOW_REAL_PROVIDER_WRITES = 'false'
process.env.ALIYUN_KMS_MODE = 'mock'
process.env.ALIYUN_OSS_REALNAME_MODE = 'mock'
process.env.ALIYUN_SMS_MODE = 'mock'
process.env.DATABASE_URL ??= 'postgresql://wanmi:wanmi_local_only@127.0.0.1:55432/wanmi'
process.env.NEXT_PUBLIC_SERVER_URL = 'http://127.0.0.1:3000'
process.env.PAYLOAD_SECRET = 'test-payload-secret-at-least-32-bytes'
process.env.PUBLIC_STORAGE_MODE = 's3'
process.env.S3_ACCESS_KEY_ID = 'wanmi-minio'
process.env.S3_BUCKET = 'wanmi-public'
process.env.S3_ENDPOINT = 'http://127.0.0.1:9000'
process.env.S3_FORCE_PATH_STYLE = 'true'
process.env.S3_REGION = 'us-east-1'
process.env.S3_SECRET_ACCESS_KEY = 'wanmi-minio-local-only'
process.env.SESSION_PEPPER = 'test-session-pepper-at-least-32-bytes'
process.env.TOTP_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString('base64')
process.env.WHO_DAT_URL = 'http://127.0.0.1:8080'
