/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    adminMfaCredentials: AdminMfaCredential;
    adminInvitations: AdminInvitation;
    customers: Customer;
    smsChallenges: SmsChallenge;
    customerSessions: CustomerSession;
    articles: Article;
    topics: Topic;
    tldPages: TldPage;
    helpPages: HelpPage;
    categories: Category;
    tags: Tag;
    media: Media;
    navigation: Navigation;
    siteSettings: SiteSetting;
    advertisers: Advertiser;
    adCreatives: AdCreative;
    adPlacements: AdPlacement;
    adSchedules: AdSchedule;
    realnameTemplates: RealnameTemplate;
    realnameDocuments: RealnameDocument;
    priceRules: PriceRule;
    quotes: Quote;
    orders: Order;
    orderEvents: OrderEvent;
    paymentNotifications: PaymentNotification;
    refunds: Refund;
    providerOperations: ProviderOperation;
    domainAssets: DomainAsset;
    renewals: Renewal;
    nameserverChanges: NameserverChange;
    manualReviews: ManualReview;
    reconciliations: Reconciliation;
    auditLogs: AuditLog;
    firstPartyEvents: FirstPartyEvent;
    toolObservabilityBuckets: ToolObservabilityBucket;
    userFeedback: UserFeedback;
    customerSecurityEvents: CustomerSecurityEvent;
    priceSnapshots: PriceSnapshot;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    adminMfaCredentials: AdminMfaCredentialsSelect<false> | AdminMfaCredentialsSelect<true>;
    adminInvitations: AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    smsChallenges: SmsChallengesSelect<false> | SmsChallengesSelect<true>;
    customerSessions: CustomerSessionsSelect<false> | CustomerSessionsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    tldPages: TldPagesSelect<false> | TldPagesSelect<true>;
    helpPages: HelpPagesSelect<false> | HelpPagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    advertisers: AdvertisersSelect<false> | AdvertisersSelect<true>;
    adCreatives: AdCreativesSelect<false> | AdCreativesSelect<true>;
    adPlacements: AdPlacementsSelect<false> | AdPlacementsSelect<true>;
    adSchedules: AdSchedulesSelect<false> | AdSchedulesSelect<true>;
    realnameTemplates: RealnameTemplatesSelect<false> | RealnameTemplatesSelect<true>;
    realnameDocuments: RealnameDocumentsSelect<false> | RealnameDocumentsSelect<true>;
    priceRules: PriceRulesSelect<false> | PriceRulesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    orderEvents: OrderEventsSelect<false> | OrderEventsSelect<true>;
    paymentNotifications: PaymentNotificationsSelect<false> | PaymentNotificationsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    providerOperations: ProviderOperationsSelect<false> | ProviderOperationsSelect<true>;
    domainAssets: DomainAssetsSelect<false> | DomainAssetsSelect<true>;
    renewals: RenewalsSelect<false> | RenewalsSelect<true>;
    nameserverChanges: NameserverChangesSelect<false> | NameserverChangesSelect<true>;
    manualReviews: ManualReviewsSelect<false> | ManualReviewsSelect<true>;
    reconciliations: ReconciliationsSelect<false> | ReconciliationsSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    firstPartyEvents: FirstPartyEventsSelect<false> | FirstPartyEventsSelect<true>;
    toolObservabilityBuckets: ToolObservabilityBucketsSelect<false> | ToolObservabilityBucketsSelect<true>;
    userFeedback: UserFeedbackSelect<false> | UserFeedbackSelect<true>;
    customerSecurityEvents: CustomerSecurityEventsSelect<false> | CustomerSecurityEventsSelect<true>;
    priceSnapshots: PriceSnapshotsSelect<false> | PriceSnapshotsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Customer;
  jobs: {
    tasks: unknown;
    workflows: {
      publishingProbe: WorkflowPublishingProbe;
      contentScheduledPublish: WorkflowContentScheduledPublish;
      backgroundProbe: WorkflowBackgroundProbe;
      commerceFulfillment: WorkflowCommerceFulfillment;
    };
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  roles: ('content_editor' | 'ad_operator' | 'analyst' | 'system_admin')[];
  status: 'active' | 'disabled';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMfaCredentials".
 */
export interface AdminMfaCredential {
  id: number;
  admin: number | Admin;
  secretEncrypted: string;
  recoveryCodeHashes?: string[] | null;
  lastUsedStep?: number | null;
  failedAttempts: number;
  lockedUntil?: string | null;
  version: number;
  configuredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminInvitations".
 */
export interface AdminInvitation {
  id: number;
  purpose: 'new_admin' | 'mfa_reset';
  email: string;
  roles: ('content_editor' | 'ad_operator' | 'analyst' | 'system_admin')[];
  targetAdmin?: (number | null) | Admin;
  tokenHash: string;
  totpSecretEncrypted: string;
  expiresAt: string;
  consumedAt?: string | null;
  revokedAt?: string | null;
  createdBy: number | Admin;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  phone: string;
  phoneMasked: string;
  status: 'active' | 'disabled' | 'deletion_requested';
  updatedAt: string;
  createdAt: string;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smsChallenges".
 */
export interface SmsChallenge {
  id: number;
  challengeId: string;
  phone: string;
  phoneHash: string;
  codeHash: string;
  ipHash: string;
  deviceHash: string;
  expiresAt: string;
  attempts: number;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customerSessions".
 */
export interface CustomerSession {
  id: number;
  customer: number | Customer;
  tokenHash: string;
  deviceHash: string;
  ipHash: string;
  expiresAt: string;
  revokedAt?: string | null;
  lastSeenAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  source?: string | null;
  workflowStatus: 'draft' | 'in_review' | 'published' | 'unpublished' | 'archived';
  scheduledPublishAt?: string | null;
  publishedAt?: string | null;
  revisionBy?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  meta?: WanmiSeoMeta;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WanmiSeoMeta".
 */
export interface WanmiSeoMeta {
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | Media;
  /**
   * 留空时按内容类型与 slug 自动生成；只允许 Wanmi 主域内的路径或完整 URL。
   */
  canonical?: string | null;
  /**
   * 启用后，已发布页面也不会进入搜索引擎索引或 sitemap。
   */
  noIndex?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  source?: string | null;
  reviewed: boolean;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  source?: string | null;
  workflowStatus: 'draft' | 'in_review' | 'published' | 'unpublished' | 'archived';
  scheduledPublishAt?: string | null;
  publishedAt?: string | null;
  revisionBy?: string | null;
  meta?: WanmiSeoMeta;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tldPages".
 */
export interface TldPage {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  source?: string | null;
  workflowStatus: 'draft' | 'in_review' | 'published' | 'unpublished' | 'archived';
  scheduledPublishAt?: string | null;
  publishedAt?: string | null;
  revisionBy?: string | null;
  meta?: WanmiSeoMeta;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpPages".
 */
export interface HelpPage {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  source?: string | null;
  workflowStatus: 'draft' | 'in_review' | 'published' | 'unpublished' | 'archived';
  scheduledPublishAt?: string | null;
  publishedAt?: string | null;
  revisionBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  label: string;
  href: string;
  order: number;
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  key: string;
  value:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertisers".
 */
export interface Advertiser {
  id: number;
  name: string;
  status: 'active' | 'paused';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adCreatives".
 */
export interface AdCreative {
  id: number;
  name: string;
  advertiser: number | Advertiser;
  image: number | Media;
  alt: string;
  targetUrl: string;
  status: 'draft' | 'approved' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adPlacements".
 */
export interface AdPlacement {
  id: number;
  code: string;
  description: string;
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adSchedules".
 */
export interface AdSchedule {
  id: number;
  creative: number | AdCreative;
  placement: number | AdPlacement;
  startsAt: string;
  endsAt: string;
  status: 'scheduled' | 'active' | 'ended' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realnameTemplates".
 */
export interface RealnameTemplate {
  id: number;
  customer: number | Customer;
  displayName: string;
  type: 'individual' | 'organization';
  status: 'draft' | 'pending_review' | 'verified' | 'rejected' | 'manual_review' | 'disabled';
  providerTemplateId?: string | null;
  safeFailureReason?: string | null;
  disabledAt?: string | null;
  cleanupDueAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realnameDocuments".
 */
export interface RealnameDocument {
  id: number;
  customer: number | Customer;
  template: number | RealnameTemplate;
  objectKey: string;
  encryptedDataKey: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priceRules".
 */
export interface PriceRule {
  id: number;
  tld: string;
  mode: 'fixed' | 'percentage';
  fixedAmountMinor: number;
  percentageBasisPoints?: number | null;
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  customer: number | Customer;
  domainAscii: string;
  years: number;
  upstreamCostMinor: number;
  userPriceMinor: number;
  currency: 'CNY';
  ruleSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | Customer;
  quote: number | Quote;
  realnameTemplate: number | RealnameTemplate;
  domainAscii: string;
  status:
    | 'pending_payment'
    | 'paid'
    | 'fulfilling'
    | 'succeeded'
    | 'refund_pending'
    | 'refunding'
    | 'refunded'
    | 'manual_review'
    | 'cancelled';
  amountMinor: number;
  currency: 'CNY';
  quoteSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orderEvents".
 */
export interface OrderEvent {
  id: number;
  order: number | Order;
  customer: number | Customer;
  fromStatus?:
    | (
        | 'pending_payment'
        | 'paid'
        | 'fulfilling'
        | 'succeeded'
        | 'refund_pending'
        | 'refunding'
        | 'refunded'
        | 'manual_review'
        | 'cancelled'
      )
    | null;
  toStatus:
    | 'pending_payment'
    | 'paid'
    | 'fulfilling'
    | 'succeeded'
    | 'refund_pending'
    | 'refunding'
    | 'refunded'
    | 'manual_review'
    | 'cancelled';
  reasonCode: string;
  note?: string | null;
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actorType: 'system' | 'customer' | 'admin' | 'provider';
  actorId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentNotifications".
 */
export interface PaymentNotification {
  id: number;
  wechatTransactionId: string;
  merchantOrderNumber: string;
  signatureVerified: boolean;
  amountMinor: number;
  receivedAt: string;
  payloadDigest: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  refundNumber: string;
  order: number | Order;
  amountMinor: number;
  status: 'pending' | 'submitted' | 'succeeded' | 'failed' | 'unknown';
  providerRefundId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providerOperations".
 */
export interface ProviderOperation {
  id: number;
  operationKey: string;
  order: number | Order;
  provider: 'westdigital' | 'wechatpay';
  operation: 'register' | 'renew' | 'refund' | 'nameserver' | 'query';
  status: 'prepared' | 'submitted' | 'succeeded' | 'failed' | 'unknown';
  providerRequestId?: string | null;
  submittedAt?: string | null;
  lastCheckedAt?: string | null;
  safeResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domainAssets".
 */
export interface DomainAsset {
  id: number;
  customer: number | Customer;
  realnameTemplate: number | RealnameTemplate;
  domainAscii: string;
  registrar: string;
  registeredAt: string;
  expiresAt: string;
  status: 'active' | 'expired' | 'pending' | 'unknown';
  nameservers: string[];
  lastSyncedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renewals".
 */
export interface Renewal {
  id: number;
  customer: number | Customer;
  asset: number | DomainAsset;
  order: number | Order;
  years: number;
  status: 'pending' | 'succeeded' | 'failed' | 'manual_review';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nameserverChanges".
 */
export interface NameserverChange {
  id: number;
  customer: number | Customer;
  asset: number | DomainAsset;
  requestedNameservers: string[];
  status: 'pending' | 'succeeded' | 'failed' | 'manual_review';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manualReviews".
 */
export interface ManualReview {
  id: number;
  order?: (number | null) | Order;
  reasonCode: string;
  status: 'open' | 'resolved';
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resolutionNote?: string | null;
  resolvedBy?: (number | null) | Admin;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reconciliations".
 */
export interface Reconciliation {
  id: number;
  kind: 'wechat' | 'westdigital' | 'three_way';
  periodStart: string;
  periodEnd: string;
  status: 'pending' | 'matched' | 'difference' | 'reviewed';
  summary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actorType: 'anonymous' | 'customer' | 'admin' | 'system' | 'provider';
  actorId?: string | null;
  targetType: string;
  targetId?: string | null;
  traceId: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firstPartyEvents".
 */
export interface FirstPartyEvent {
  id: number;
  schemaVersion: number;
  event: 'page_viewed' | 'tool_submitted' | 'tool_completed' | 'tool_failed';
  pageType?: ('home' | 'tool_index' | 'tool' | 'pricing' | 'content_index' | 'help' | 'legal' | 'other') | null;
  source?: ('direct' | 'internal' | 'search' | 'social' | 'referral') | null;
  deviceCategory?: ('mobile' | 'tablet' | 'desktop') | null;
  tool?: ('domain-search' | 'whois' | 'dns' | 'ssl-check' | 'idn' | 'pricing') | null;
  inputType?: ('full_domain' | 'keyword' | 'unknown') | null;
  fromLocalHistory?: boolean | null;
  tld?: string | null;
  resultCategory?: ('ready' | 'empty' | 'partial' | 'degraded') | null;
  succeeded?: boolean | null;
  durationBucket?: ('lt_100ms' | '100_299ms' | '300_999ms' | '1000_2999ms' | '3000_9999ms' | 'gte_10000ms') | null;
  dataSource?: ('local' | 'cache' | 'westdigital' | 'whodat' | 'dns' | 'tls' | 'unknown') | null;
  errorCode?: string | null;
  traceId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "toolObservabilityBuckets".
 */
export interface ToolObservabilityBucket {
  id: number;
  schemaVersion: number;
  bucketKey: string;
  bucketStart: string;
  bucketEnd: string;
  lastObservedAt: string;
  scope: 'tool' | 'provider';
  tool?: ('domain-search' | 'whois' | 'dns' | 'ssl-check' | 'idn' | 'pricing') | null;
  provider?: ('westdigital' | 'whodat' | 'alidns' | 'node_tls') | null;
  providerOperation?: ('availability' | 'price' | 'whois' | 'dns' | 'tls') | null;
  requestCount: number;
  successCount: number;
  failureCount: number;
  successRateBasisPoints: number;
  p50Bucket?: ('lt_100ms' | '100_299ms' | '300_999ms' | '1000_2999ms' | '3000_9999ms' | 'gte_10000ms') | null;
  p95Bucket?: ('lt_100ms' | '100_299ms' | '300_999ms' | '1000_2999ms' | '3000_9999ms' | 'gte_10000ms') | null;
  latencyLt100MsCount: number;
  latency100To299MsCount: number;
  latency300To999MsCount: number;
  latency1000To2999MsCount: number;
  latency3000To9999MsCount: number;
  latencyGte10000MsCount: number;
  timeoutErrorCount: number;
  rateLimitedErrorCount: number;
  upstreamErrorCount: number;
  invalidResponseErrorCount: number;
  lastQueueDepth: number;
  maxQueueDepth: number;
  rejectedCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userFeedback".
 */
export interface UserFeedback {
  id: number;
  customer?: (number | null) | Customer;
  category: 'contact' | 'feedback' | 'request';
  message: string;
  status: 'new' | 'reviewed' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customerSecurityEvents".
 */
export interface CustomerSecurityEvent {
  id: number;
  customer: number | Customer;
  event: string;
  occurredAt: string;
  safeMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priceSnapshots".
 */
export interface PriceSnapshot {
  id: number;
  schemaVersion: number;
  calculationVersion: number;
  snapshotRef: string;
  calculationHash: string;
  tld: string;
  representativeDomainAscii: string;
  priceClass: 'standard';
  currency: 'CNY';
  provider: 'westdigital_fixture';
  providerProductId: string;
  providerRequestId: string;
  providerObservedAt: string;
  providerCacheStatus: 'hit' | 'miss';
  providerCacheExpiresAt?: string | null;
  ruleSource: 'wanmi_fixture';
  ruleKey: string;
  ruleVersion: number;
  ruleMode: 'fixed' | 'percentage';
  ruleFixedAmountMinor?: number | null;
  rulePercentageBasisPoints?: number | null;
  roundingMode: 'half_up_to_fen';
  upstreamRegistrationPriceMinor: number;
  upstreamRenewalPriceMinor: number;
  registrationPriceMinor: number;
  renewalPriceMinor: number;
  oneYearTotalMinor: number;
  threeYearTotalMinor: number;
  calculationFormula: 'registration_price_plus_annual_renewal_price';
  createdTraceId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'topics';
          value: number | Topic;
        } | null)
      | ({
          relationTo: 'tldPages';
          value: number | TldPage;
        } | null);
    url?: string | null;
  };
  type: '301';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'topics';
          value: number | Topic;
        } | null)
      | ({
          relationTo: 'tldPages';
          value: number | TldPage;
        } | null);
    url?: string | null;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  purpose: 'contact' | 'feedback' | 'request';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: 'inline' | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  workflowSlug?: ('publishingProbe' | 'contentScheduledPublish' | 'backgroundProbe' | 'commerceFulfillment') | null;
  taskSlug?: 'inline' | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'adminMfaCredentials';
        value: number | AdminMfaCredential;
      } | null)
    | ({
        relationTo: 'adminInvitations';
        value: number | AdminInvitation;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'smsChallenges';
        value: number | SmsChallenge;
      } | null)
    | ({
        relationTo: 'customerSessions';
        value: number | CustomerSession;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'tldPages';
        value: number | TldPage;
      } | null)
    | ({
        relationTo: 'helpPages';
        value: number | HelpPage;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'siteSettings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'advertisers';
        value: number | Advertiser;
      } | null)
    | ({
        relationTo: 'adCreatives';
        value: number | AdCreative;
      } | null)
    | ({
        relationTo: 'adPlacements';
        value: number | AdPlacement;
      } | null)
    | ({
        relationTo: 'adSchedules';
        value: number | AdSchedule;
      } | null)
    | ({
        relationTo: 'realnameTemplates';
        value: number | RealnameTemplate;
      } | null)
    | ({
        relationTo: 'realnameDocuments';
        value: number | RealnameDocument;
      } | null)
    | ({
        relationTo: 'priceRules';
        value: number | PriceRule;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'orderEvents';
        value: number | OrderEvent;
      } | null)
    | ({
        relationTo: 'paymentNotifications';
        value: number | PaymentNotification;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null)
    | ({
        relationTo: 'providerOperations';
        value: number | ProviderOperation;
      } | null)
    | ({
        relationTo: 'domainAssets';
        value: number | DomainAsset;
      } | null)
    | ({
        relationTo: 'renewals';
        value: number | Renewal;
      } | null)
    | ({
        relationTo: 'nameserverChanges';
        value: number | NameserverChange;
      } | null)
    | ({
        relationTo: 'manualReviews';
        value: number | ManualReview;
      } | null)
    | ({
        relationTo: 'reconciliations';
        value: number | Reconciliation;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'firstPartyEvents';
        value: number | FirstPartyEvent;
      } | null)
    | ({
        relationTo: 'userFeedback';
        value: number | UserFeedback;
      } | null)
    | ({
        relationTo: 'customerSecurityEvents';
        value: number | CustomerSecurityEvent;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  roles?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMfaCredentials_select".
 */
export interface AdminMfaCredentialsSelect<T extends boolean = true> {
  admin?: T;
  secretEncrypted?: T;
  recoveryCodeHashes?: T;
  lastUsedStep?: T;
  failedAttempts?: T;
  lockedUntil?: T;
  version?: T;
  configuredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminInvitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  purpose?: T;
  email?: T;
  roles?: T;
  targetAdmin?: T;
  tokenHash?: T;
  totpSecretEncrypted?: T;
  expiresAt?: T;
  consumedAt?: T;
  revokedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  phone?: T;
  phoneMasked?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smsChallenges_select".
 */
export interface SmsChallengesSelect<T extends boolean = true> {
  challengeId?: T;
  phone?: T;
  phoneHash?: T;
  codeHash?: T;
  ipHash?: T;
  deviceHash?: T;
  expiresAt?: T;
  attempts?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customerSessions_select".
 */
export interface CustomerSessionsSelect<T extends boolean = true> {
  customer?: T;
  tokenHash?: T;
  deviceHash?: T;
  ipHash?: T;
  expiresAt?: T;
  revokedAt?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  source?: T;
  workflowStatus?: T;
  scheduledPublishAt?: T;
  publishedAt?: T;
  revisionBy?: T;
  categories?: T;
  tags?: T;
  meta?: T | WanmiSeoMetaSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WanmiSeoMeta_select".
 */
export interface WanmiSeoMetaSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  canonical?: T;
  noIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  source?: T;
  workflowStatus?: T;
  scheduledPublishAt?: T;
  publishedAt?: T;
  revisionBy?: T;
  meta?: T | WanmiSeoMetaSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tldPages_select".
 */
export interface TldPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  source?: T;
  workflowStatus?: T;
  scheduledPublishAt?: T;
  publishedAt?: T;
  revisionBy?: T;
  meta?: T | WanmiSeoMetaSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpPages_select".
 */
export interface HelpPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  source?: T;
  workflowStatus?: T;
  scheduledPublishAt?: T;
  publishedAt?: T;
  revisionBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  source?: T;
  reviewed?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertisers_select".
 */
export interface AdvertisersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adCreatives_select".
 */
export interface AdCreativesSelect<T extends boolean = true> {
  name?: T;
  advertiser?: T;
  image?: T;
  alt?: T;
  targetUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adPlacements_select".
 */
export interface AdPlacementsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adSchedules_select".
 */
export interface AdSchedulesSelect<T extends boolean = true> {
  creative?: T;
  placement?: T;
  startsAt?: T;
  endsAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realnameTemplates_select".
 */
export interface RealnameTemplatesSelect<T extends boolean = true> {
  customer?: T;
  displayName?: T;
  type?: T;
  status?: T;
  providerTemplateId?: T;
  safeFailureReason?: T;
  disabledAt?: T;
  cleanupDueAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realnameDocuments_select".
 */
export interface RealnameDocumentsSelect<T extends boolean = true> {
  customer?: T;
  template?: T;
  objectKey?: T;
  encryptedDataKey?: T;
  contentType?: T;
  sizeBytes?: T;
  sha256?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priceRules_select".
 */
export interface PriceRulesSelect<T extends boolean = true> {
  tld?: T;
  mode?: T;
  fixedAmountMinor?: T;
  percentageBasisPoints?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  customer?: T;
  domainAscii?: T;
  years?: T;
  upstreamCostMinor?: T;
  userPriceMinor?: T;
  currency?: T;
  ruleSnapshot?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  quote?: T;
  realnameTemplate?: T;
  domainAscii?: T;
  status?: T;
  amountMinor?: T;
  currency?: T;
  quoteSnapshot?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orderEvents_select".
 */
export interface OrderEventsSelect<T extends boolean = true> {
  order?: T;
  customer?: T;
  fromStatus?: T;
  toStatus?: T;
  reasonCode?: T;
  note?: T;
  evidence?: T;
  actorType?: T;
  actorId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentNotifications_select".
 */
export interface PaymentNotificationsSelect<T extends boolean = true> {
  wechatTransactionId?: T;
  merchantOrderNumber?: T;
  signatureVerified?: T;
  amountMinor?: T;
  receivedAt?: T;
  payloadDigest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  refundNumber?: T;
  order?: T;
  amountMinor?: T;
  status?: T;
  providerRefundId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providerOperations_select".
 */
export interface ProviderOperationsSelect<T extends boolean = true> {
  operationKey?: T;
  order?: T;
  provider?: T;
  operation?: T;
  status?: T;
  providerRequestId?: T;
  submittedAt?: T;
  lastCheckedAt?: T;
  safeResult?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domainAssets_select".
 */
export interface DomainAssetsSelect<T extends boolean = true> {
  customer?: T;
  realnameTemplate?: T;
  domainAscii?: T;
  registrar?: T;
  registeredAt?: T;
  expiresAt?: T;
  status?: T;
  nameservers?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renewals_select".
 */
export interface RenewalsSelect<T extends boolean = true> {
  customer?: T;
  asset?: T;
  order?: T;
  years?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nameserverChanges_select".
 */
export interface NameserverChangesSelect<T extends boolean = true> {
  customer?: T;
  asset?: T;
  requestedNameservers?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manualReviews_select".
 */
export interface ManualReviewsSelect<T extends boolean = true> {
  order?: T;
  reasonCode?: T;
  status?: T;
  evidence?: T;
  resolutionNote?: T;
  resolvedBy?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reconciliations_select".
 */
export interface ReconciliationsSelect<T extends boolean = true> {
  kind?: T;
  periodStart?: T;
  periodEnd?: T;
  status?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  actorId?: T;
  targetType?: T;
  targetId?: T;
  traceId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firstPartyEvents_select".
 */
export interface FirstPartyEventsSelect<T extends boolean = true> {
  schemaVersion?: T;
  event?: T;
  pageType?: T;
  source?: T;
  deviceCategory?: T;
  tool?: T;
  inputType?: T;
  fromLocalHistory?: T;
  tld?: T;
  resultCategory?: T;
  succeeded?: T;
  durationBucket?: T;
  dataSource?: T;
  errorCode?: T;
  traceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "toolObservabilityBuckets_select".
 */
export interface ToolObservabilityBucketsSelect<T extends boolean = true> {
  schemaVersion?: T;
  bucketKey?: T;
  bucketStart?: T;
  bucketEnd?: T;
  lastObservedAt?: T;
  scope?: T;
  tool?: T;
  provider?: T;
  providerOperation?: T;
  requestCount?: T;
  successCount?: T;
  failureCount?: T;
  successRateBasisPoints?: T;
  p50Bucket?: T;
  p95Bucket?: T;
  latencyLt100MsCount?: T;
  latency100To299MsCount?: T;
  latency300To999MsCount?: T;
  latency1000To2999MsCount?: T;
  latency3000To9999MsCount?: T;
  latencyGte10000MsCount?: T;
  timeoutErrorCount?: T;
  rateLimitedErrorCount?: T;
  upstreamErrorCount?: T;
  invalidResponseErrorCount?: T;
  lastQueueDepth?: T;
  maxQueueDepth?: T;
  rejectedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userFeedback_select".
 */
export interface UserFeedbackSelect<T extends boolean = true> {
  customer?: T;
  category?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customerSecurityEvents_select".
 */
export interface CustomerSecurityEventsSelect<T extends boolean = true> {
  customer?: T;
  event?: T;
  occurredAt?: T;
  safeMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priceSnapshots_select".
 */
export interface PriceSnapshotsSelect<T extends boolean = true> {
  schemaVersion?: T;
  calculationVersion?: T;
  snapshotRef?: T;
  calculationHash?: T;
  tld?: T;
  representativeDomainAscii?: T;
  priceClass?: T;
  currency?: T;
  provider?: T;
  providerProductId?: T;
  providerRequestId?: T;
  providerObservedAt?: T;
  providerCacheStatus?: T;
  providerCacheExpiresAt?: T;
  ruleSource?: T;
  ruleKey?: T;
  ruleVersion?: T;
  ruleMode?: T;
  ruleFixedAmountMinor?: T;
  rulePercentageBasisPoints?: T;
  roundingMode?: T;
  upstreamRegistrationPriceMinor?: T;
  upstreamRenewalPriceMinor?: T;
  registrationPriceMinor?: T;
  renewalPriceMinor?: T;
  oneYearTotalMinor?: T;
  threeYearTotalMinor?: T;
  calculationFormula?: T;
  createdTraceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  purpose?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowPublishingProbe".
 */
export interface WorkflowPublishingProbe {
  input: {
    traceId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowContentScheduledPublish".
 */
export interface WorkflowContentScheduledPublish {
  input: {
    collection: 'articles' | 'topics' | 'tldPages' | 'helpPages';
    documentId: string;
    publishAt: string;
    scheduledBy: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowBackgroundProbe".
 */
export interface WorkflowBackgroundProbe {
  input: {
    traceId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowCommerceFulfillment".
 */
export interface WorkflowCommerceFulfillment {
  input: {
    operationKey: string;
    orderId: number;
    traceId: string;
    simulate?: ('success' | 'timeout-before-submit' | 'timeout-after-submit') | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}