import type { CollectionConfig } from 'payload'

import { AdminAccessEvents, AdminApprovalRequests } from './administration'
import { AdCreatives, AdMedia, AdPlacements, AdSchedules, Advertisers } from './advertising'
import {
  OrderEvents,
  OrderManualActions,
  Orders,
  PaymentNotificationArchives,
  PaymentNotifications,
  PriceRules,
  PriceSnapshots,
  Quotes,
  RefundNotifications,
  Refunds,
} from './commerce'
import {
  Articles,
  Categories,
  HelpPages,
  Media,
  Navigation,
  SiteSettings,
  Tags,
  TldPages,
  ToolPages,
  Topics,
} from './content'
import { DnsRecordChanges } from './dns-management'
import {
  DomainAssetSyncEvents,
  DomainBatchOperationEvents,
  DomainManagementEvents,
} from './domain-management'
import {
  DomainAssets,
  AutomaticRenewalEvents,
  DomainExpiryReminders,
  NameserverChanges,
  ProviderOperations,
  ProviderWriteBudgetDebits,
  ProviderWriteBudgets,
  RenewalMandates,
  Renewals,
} from './fulfillment'
import {
  AccountClosureRequests,
  AccountRecoveryRecords,
  AdminInvitations,
  AdminMfaCredentials,
  Admins,
  ConsentRecords,
  CustomerIdentities,
  CustomerRegistrationIntents,
  Customers,
  CustomerSessions,
  SmsChallenges,
  SmsRateLimits,
  StepUpGrants,
  WechatAuthorizationCodes,
  WechatLoginScenes,
  WechatOAuthStates,
} from './identity'
import {
  AuditLogs,
  CustomerSecurityEvents,
  FirstPartyEvents,
  ManualReviews,
  Reconciliations,
  ToolObservabilityBuckets,
  UserFeedback,
} from './operations'
import {
  NotificationDeliveries,
  NotificationMarketingPreferences,
  NotificationOutboxEvents,
  NotificationProviderReceipts,
  NotificationReadStates,
} from './notifications'
import {
  PointsAccounts,
  PointsBatches,
  PointsConsumptionAllocations,
  PointsLedger,
  PointsRedemptions,
  ToolQuotaLedger,
} from './points'
import { RealnameDocuments, RealnameTemplates } from './realname'
import {
  WalletAccounts,
  WalletEntries,
  WalletPolicyVersions,
  WalletTopUpOrders,
  WalletTransactions,
} from './wallet'

export const collections: CollectionConfig[] = [
  Admins,
  AdminApprovalRequests,
  AdminAccessEvents,
  AdminMfaCredentials,
  AdminInvitations,
  Customers,
  AccountClosureRequests,
  AccountRecoveryRecords,
  CustomerIdentities,
  ConsentRecords,
  CustomerRegistrationIntents,
  WechatOAuthStates,
  WechatAuthorizationCodes,
  WechatLoginScenes,
  SmsChallenges,
  SmsRateLimits,
  CustomerSessions,
  StepUpGrants,
  Articles,
  Topics,
  TldPages,
  HelpPages,
  Categories,
  Tags,
  ToolPages,
  Media,
  Navigation,
  SiteSettings,
  Advertisers,
  AdMedia,
  AdCreatives,
  AdPlacements,
  AdSchedules,
  RealnameTemplates,
  RealnameDocuments,
  PriceRules,
  Quotes,
  Orders,
  OrderEvents,
  PaymentNotifications,
  PaymentNotificationArchives,
  OrderManualActions,
  RefundNotifications,
  Refunds,
  WalletAccounts,
  WalletTransactions,
  WalletEntries,
  WalletTopUpOrders,
  WalletPolicyVersions,
  PointsAccounts,
  PointsBatches,
  PointsRedemptions,
  PointsLedger,
  PointsConsumptionAllocations,
  ToolQuotaLedger,
  ProviderOperations,
  ProviderWriteBudgets,
  ProviderWriteBudgetDebits,
  DomainAssets,
  DomainExpiryReminders,
  Renewals,
  NameserverChanges,
  DnsRecordChanges,
  DomainManagementEvents,
  DomainAssetSyncEvents,
  DomainBatchOperationEvents,
  RenewalMandates,
  AutomaticRenewalEvents,
  ManualReviews,
  Reconciliations,
  AuditLogs,
  FirstPartyEvents,
  ToolObservabilityBuckets,
  UserFeedback,
  CustomerSecurityEvents,
  NotificationOutboxEvents,
  NotificationDeliveries,
  NotificationProviderReceipts,
  NotificationReadStates,
  NotificationMarketingPreferences,
  PriceSnapshots,
]
