import type { CollectionConfig } from 'payload'

import { AdCreatives, AdMedia, AdPlacements, AdSchedules, Advertisers } from './advertising'
import {
  OrderEvents,
  OrderManualActions,
  Orders,
  PaymentNotificationArchives,
  PaymentNotifications,
  PriceRules,
  PriceSnapshots,
  Quotes,
  RefundNotifications,
  Refunds,
} from './commerce'
import {
  Articles,
  Categories,
  HelpPages,
  Media,
  Navigation,
  SiteSettings,
  Tags,
  TldPages,
  ToolPages,
  Topics,
} from './content'
import {
  DomainAssets,
  DomainExpiryReminders,
  NameserverChanges,
  ProviderOperations,
  ProviderWriteBudgetDebits,
  ProviderWriteBudgets,
  Renewals,
} from './fulfillment'
import {
  AdminInvitations,
  AdminMfaCredentials,
  Admins,
  ConsentRecords,
  CustomerIdentities,
  CustomerRegistrationIntents,
  Customers,
  CustomerSessions,
  SmsChallenges,
  SmsRateLimits,
  WechatAuthorizationCodes,
  WechatLoginScenes,
  WechatOAuthStates,
} from './identity'
import {
  AuditLogs,
  CustomerSecurityEvents,
  FirstPartyEvents,
  ManualReviews,
  Reconciliations,
  ToolObservabilityBuckets,
  UserFeedback,
} from './operations'
import { RealnameDocuments, RealnameTemplates } from './realname'

export const collections: CollectionConfig[] = [
  Admins,
  AdminMfaCredentials,
  AdminInvitations,
  Customers,
  CustomerIdentities,
  ConsentRecords,
  CustomerRegistrationIntents,
  WechatOAuthStates,
  WechatAuthorizationCodes,
  WechatLoginScenes,
  SmsChallenges,
  SmsRateLimits,
  CustomerSessions,
  Articles,
  Topics,
  TldPages,
  HelpPages,
  Categories,
  Tags,
  ToolPages,
  Media,
  Navigation,
  SiteSettings,
  Advertisers,
  AdMedia,
  AdCreatives,
  AdPlacements,
  AdSchedules,
  RealnameTemplates,
  RealnameDocuments,
  PriceRules,
  Quotes,
  Orders,
  OrderEvents,
  PaymentNotifications,
  PaymentNotificationArchives,
  OrderManualActions,
  RefundNotifications,
  Refunds,
  ProviderOperations,
  ProviderWriteBudgets,
  ProviderWriteBudgetDebits,
  DomainAssets,
  DomainExpiryReminders,
  Renewals,
  NameserverChanges,
  ManualReviews,
  Reconciliations,
  AuditLogs,
  FirstPartyEvents,
  ToolObservabilityBuckets,
  UserFeedback,
  CustomerSecurityEvents,
  PriceSnapshots,
]
