import type { CollectionConfig } from 'payload'

import { AdCreatives, AdMedia, AdPlacements, AdSchedules, Advertisers } from './advertising'
import {
  OrderEvents,
  Orders,
  PaymentNotifications,
  PriceRules,
  PriceSnapshots,
  Quotes,
  Refunds,
} from './commerce'
import {
  Articles,
  Categories,
  HelpPages,
  Media,
  Navigation,
  SiteSettings,
  Tags,
  TldPages,
  ToolPages,
  Topics,
} from './content'
import { DomainAssets, NameserverChanges, ProviderOperations, Renewals } from './fulfillment'
import {
  AdminInvitations,
  AdminMfaCredentials,
  Admins,
  Customers,
  CustomerSessions,
  SmsChallenges,
  SmsRateLimits,
} from './identity'
import {
  AuditLogs,
  CustomerSecurityEvents,
  FirstPartyEvents,
  ManualReviews,
  Reconciliations,
  ToolObservabilityBuckets,
  UserFeedback,
} from './operations'
import { RealnameDocuments, RealnameTemplates } from './realname'

export const collections: CollectionConfig[] = [
  Admins,
  AdminMfaCredentials,
  AdminInvitations,
  Customers,
  SmsChallenges,
  SmsRateLimits,
  CustomerSessions,
  Articles,
  Topics,
  TldPages,
  HelpPages,
  Categories,
  Tags,
  ToolPages,
  Media,
  Navigation,
  SiteSettings,
  Advertisers,
  AdMedia,
  AdCreatives,
  AdPlacements,
  AdSchedules,
  RealnameTemplates,
  RealnameDocuments,
  PriceRules,
  Quotes,
  Orders,
  OrderEvents,
  PaymentNotifications,
  Refunds,
  ProviderOperations,
  DomainAssets,
  Renewals,
  NameserverChanges,
  ManualReviews,
  Reconciliations,
  AuditLogs,
  FirstPartyEvents,
  ToolObservabilityBuckets,
  UserFeedback,
  CustomerSecurityEvents,
  PriceSnapshots,
]
