import type { CollectionConfig } from 'payload'

import {
  adManagerFieldRead,
  analystAdminHidden,
  analysts,
  auditAdminHidden,
  auditReaders,
  deny,
  operationalReaders,
  operationsAdminHidden,
  ownOrSystem,
  sensitiveFieldRead,
  systemAdminHidden,
  systemAdminOnly,
} from '@/access/roles'
import { ADMIN_GROUPS } from '@/lib/admin-navigation'
import {
  TOOL_OBSERVABILITY_PROVIDERS,
  TOOL_OBSERVABILITY_PROVIDER_OPERATIONS,
} from '@/services/observability/tool-observability'
import { FIRST_PARTY_DURATION_BUCKETS, FIRST_PARTY_TOOLS } from '@/schemas/analytics'

export const ManualReviews: CollectionConfig = {
  slug: 'manualReviews',
  access: { create: deny, delete: deny, read: systemAdminOnly, update: deny },
  admin: { group: ADMIN_GROUPS.operations, hidden: systemAdminHidden },
  fields: [
    { name: 'customer', type: 'relationship', relationTo: 'customers', index: true },
    {
      name: 'customerIdentity',
      type: 'relationship',
      relationTo: 'customerIdentities',
      index: true,
    },
    { name: 'order', type: 'relationship', relationTo: 'orders', index: true },
    {
      name: 'realnameTemplate',
      type: 'relationship',
      relationTo: 'realnameTemplates',
      index: true,
    },
    {
      name: 'paymentNotification',
      type: 'relationship',
      relationTo: 'paymentNotifications',
      index: true,
    },
    {
      name: 'walletTopUpOrder',
      type: 'relationship',
      relationTo: 'walletTopUpOrders',
      index: true,
    },
    {
      name: 'walletAccount',
      type: 'relationship',
      relationTo: 'walletAccounts',
      index: true,
    },
    {
      name: 'invitationRewardClaim',
      type: 'relationship',
      relationTo: 'invitationRewardClaims',
      index: true,
      unique: true,
    },
    {
      name: 'reconciliation',
      type: 'relationship',
      relationTo: 'reconciliations',
      index: true,
      unique: true,
    },
    {
      name: 'domainAsset',
      type: 'relationship',
      relationTo: 'domainAssets',
      index: true,
    },
    {
      name: 'nameserverChange',
      type: 'relationship',
      relationTo: 'nameserverChanges',
      index: true,
    },
    { name: 'reasonCode', type: 'text', index: true, required: true },
    {
      name: 'status',
      type: 'select',
      options: ['open', 'resolved'],
      defaultValue: 'open',
      required: true,
    },
    { name: 'evidence', type: 'json' },
    { name: 'resolutionNote', type: 'textarea' },
    { name: 'resolvedBy', type: 'relationship', relationTo: 'admins' },
    { name: 'resolvedAt', type: 'date' },
  ],
}

export const Reconciliations: CollectionConfig = {
  slug: 'reconciliations',
  access: { create: deny, delete: deny, read: operationalReaders, update: deny },
  admin: { group: ADMIN_GROUPS.operations, hidden: operationsAdminHidden },
  fields: [
    { name: 'reconciliationKey', type: 'text', index: true, required: true, unique: true },
    {
      name: 'kind',
      type: 'select',
      options: ['wechat', 'westdigital', 'three_way', 'wallet'],
      required: true,
    },
    {
      name: 'ledger',
      type: 'select',
      options: ['wechat_funds', 'westdigital_prepaid', 'internal_orders', 'wallet_balance'],
      required: true,
    },
    { name: 'recordKey', type: 'text', index: true, required: true },
    { name: 'periodStart', type: 'date', required: true },
    { name: 'periodEnd', type: 'date', required: true },
    {
      name: 'status',
      type: 'select',
      options: ['pending', 'matched', 'difference', 'reviewed'],
      required: true,
    },
    { name: 'summary', type: 'json', required: true },
    { name: 'differenceMinor', type: 'number', required: true },
    { name: 'currency', type: 'select', options: ['CNY'], required: true },
    { name: 'traceId', type: 'text', index: true, required: true },
  ],
  indexes: [{ fields: ['ledger', 'periodStart', 'periodEnd'] }],
}

export const AuditLogs: CollectionConfig = {
  slug: 'auditLogs',
  access: { create: deny, delete: deny, read: auditReaders, update: deny },
  admin: {
    defaultColumns: ['action', 'actorType', 'targetType', 'targetId', 'traceId', 'createdAt'],
    group: ADMIN_GROUPS.operations,
    hidden: auditAdminHidden,
    listSearchableFields: ['action', 'actorId', 'targetType', 'targetId', 'traceId'],
    useAsTitle: 'action',
  },
  defaultSort: '-createdAt',
  indexes: [{ fields: ['actorType', 'actorId', 'createdAt'] }],
  labels: { plural: '审计日志', singular: '审计事件' },
  fields: [
    { name: 'action', type: 'text', index: true, required: true },
    {
      name: 'actorType',
      type: 'select',
      options: ['anonymous', 'customer', 'admin', 'system', 'provider'],
      required: true,
    },
    { name: 'actorId', type: 'text' },
    { name: 'targetType', type: 'text', required: true },
    { name: 'targetId', type: 'text' },
    { name: 'traceId', type: 'text', index: true, required: true },
    { name: 'metadata', type: 'json', access: { read: sensitiveFieldRead } },
  ],
}

export const FirstPartyEvents: CollectionConfig = {
  slug: 'firstPartyEvents',
  access: { create: deny, delete: deny, read: systemAdminOnly, update: deny },
  admin: {
    defaultColumns: ['event', 'pageType', 'tool', 'campaignId', 'placementCode', 'createdAt'],
    group: ADMIN_GROUPS.operations,
    hidden: systemAdminHidden,
    useAsTitle: 'event',
  },
  defaultSort: '-createdAt',
  indexes: [
    { fields: ['event', 'createdAt'] },
    { fields: ['tool', 'createdAt'] },
    { fields: ['campaignId', 'event', 'createdAt'] },
  ],
  labels: { plural: '第一方事件', singular: '第一方事件' },
  fields: [
    { name: 'schemaVersion', type: 'number', defaultValue: 1, max: 1, min: 1, required: true },
    {
      name: 'event',
      type: 'select',
      options: [
        'page_viewed',
        'tool_submitted',
        'tool_completed',
        'tool_failed',
        'ad_requested',
        'ad_served',
        'ad_viewable',
        'ad_clicked',
        'ad_converted',
      ],
      required: true,
    },
    {
      name: 'pageType',
      type: 'select',
      options: [
        'home',
        'tool_index',
        'tool',
        'pricing',
        'content_index',
        'content',
        'tld',
        'help',
        'legal',
        'other',
      ],
    },
    {
      name: 'source',
      type: 'select',
      options: ['direct', 'internal', 'search', 'social', 'referral'],
    },
    {
      name: 'deviceCategory',
      type: 'select',
      options: ['mobile', 'tablet', 'desktop'],
    },
    {
      name: 'tool',
      type: 'select',
      options: ['domain-search', 'whois', 'dns', 'ssl-check', 'idn', 'pricing'],
    },
    {
      name: 'inputType',
      type: 'select',
      options: ['full_domain', 'keyword', 'unknown'],
    },
    { name: 'fromLocalHistory', type: 'checkbox' },
    { name: 'tld', type: 'text' },
    {
      name: 'resultCategory',
      type: 'select',
      options: ['ready', 'empty', 'partial', 'degraded'],
    },
    { name: 'succeeded', type: 'checkbox' },
    {
      name: 'durationBucket',
      type: 'select',
      options: ['lt_100ms', '100_299ms', '300_999ms', '1000_2999ms', '3000_9999ms', 'gte_10000ms'],
    },
    {
      name: 'dataSource',
      type: 'select',
      options: ['local', 'cache', 'westdigital', 'whodat', 'dns', 'tls', 'unknown'],
    },
    { name: 'errorCode', type: 'text' },
    { name: 'campaignId', type: 'text' },
    { name: 'placementCode', type: 'text' },
    {
      name: 'conversionType',
      type: 'select',
      options: ['landing_viewed'],
    },
    { name: 'traceId', type: 'text', index: true, required: true, unique: true },
  ],
}

export const ToolObservabilityBuckets: CollectionConfig = {
  slug: 'toolObservabilityBuckets',
  access: { create: deny, delete: deny, read: analysts, update: deny },
  admin: {
    defaultColumns: [
      'bucketStart',
      'scope',
      'tool',
      'provider',
      'providerOperation',
      'requestCount',
      'successRateBasisPoints',
      'p50Bucket',
      'p95Bucket',
      'maxQueueDepth',
      'rejectedCount',
    ],
    group: ADMIN_GROUPS.operations,
    hidden: analystAdminHidden,
    useAsTitle: 'bucketKey',
  },
  defaultSort: '-bucketStart',
  indexes: [
    { fields: ['scope', 'bucketStart'] },
    { fields: ['tool', 'bucketStart'] },
    { fields: ['provider', 'bucketStart'] },
  ],
  labels: { plural: '工具监控聚合', singular: '工具监控聚合桶' },
  lockDocuments: false,
  fields: [
    { name: 'schemaVersion', type: 'number', defaultValue: 1, max: 1, min: 1, required: true },
    { name: 'bucketKey', type: 'text', index: true, required: true, unique: true },
    { name: 'bucketStart', type: 'date', index: true, label: '小时桶开始', required: true },
    { name: 'bucketEnd', type: 'date', label: '小时桶结束', required: true },
    { name: 'lastObservedAt', type: 'date', label: '最后观测时间', required: true },
    {
      name: 'scope',
      type: 'select',
      label: '范围',
      options: ['tool', 'provider'],
      required: true,
    },
    { name: 'tool', type: 'select', label: '工具', options: [...FIRST_PARTY_TOOLS] },
    {
      name: 'provider',
      type: 'select',
      label: 'Provider',
      options: [...TOOL_OBSERVABILITY_PROVIDERS],
    },
    {
      name: 'providerOperation',
      type: 'select',
      label: 'Provider 操作',
      options: [...TOOL_OBSERVABILITY_PROVIDER_OPERATIONS],
    },
    {
      name: 'requestCount',
      type: 'number',
      defaultValue: 0,
      label: '请求量',
      min: 0,
      required: true,
    },
    {
      name: 'successCount',
      type: 'number',
      defaultValue: 0,
      label: '成功数',
      min: 0,
      required: true,
    },
    {
      name: 'failureCount',
      type: 'number',
      defaultValue: 0,
      label: '失败数',
      min: 0,
      required: true,
    },
    {
      name: 'successRateBasisPoints',
      type: 'number',
      defaultValue: 0,
      label: '成功率（基点，10000=100%）',
      max: 10_000,
      min: 0,
      required: true,
    },
    {
      name: 'p50Bucket',
      type: 'select',
      label: '延迟 P50 桶',
      options: [...FIRST_PARTY_DURATION_BUCKETS],
    },
    {
      name: 'p95Bucket',
      type: 'select',
      label: '延迟 P95 桶',
      options: [...FIRST_PARTY_DURATION_BUCKETS],
    },
    { name: 'latencyLt100MsCount', type: 'number', defaultValue: 0, min: 0, required: true },
    {
      name: 'latency100To299MsCount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      required: true,
    },
    {
      name: 'latency300To999MsCount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      required: true,
    },
    {
      name: 'latency1000To2999MsCount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      required: true,
    },
    {
      name: 'latency3000To9999MsCount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      required: true,
    },
    {
      name: 'latencyGte10000MsCount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      required: true,
    },
    {
      name: 'timeoutErrorCount',
      type: 'number',
      defaultValue: 0,
      label: '超时错误数',
      min: 0,
      required: true,
    },
    {
      name: 'rateLimitedErrorCount',
      type: 'number',
      defaultValue: 0,
      label: '限频错误数',
      min: 0,
      required: true,
    },
    {
      name: 'upstreamErrorCount',
      type: 'number',
      defaultValue: 0,
      label: '上游错误数',
      min: 0,
      required: true,
    },
    {
      name: 'invalidResponseErrorCount',
      type: 'number',
      defaultValue: 0,
      label: '无效响应数',
      min: 0,
      required: true,
    },
    {
      name: 'lastQueueDepth',
      type: 'number',
      defaultValue: 0,
      label: '最后队列深度',
      min: 0,
      required: true,
    },
    {
      name: 'maxQueueDepth',
      type: 'number',
      defaultValue: 0,
      label: '最大队列深度',
      min: 0,
      required: true,
    },
    {
      name: 'rejectedCount',
      type: 'number',
      defaultValue: 0,
      label: '被拒次数',
      min: 0,
      required: true,
    },
  ],
}

export const UserFeedback: CollectionConfig = {
  slug: 'userFeedback',
  access: { create: deny, delete: deny, read: operationalReaders, update: systemAdminOnly },
  admin: { group: ADMIN_GROUPS.operations, hidden: operationsAdminHidden },
  fields: [
    {
      name: 'customer',
      type: 'relationship',
      access: { read: sensitiveFieldRead },
      relationTo: 'customers',
    },
    {
      name: 'category',
      type: 'select',
      options: ['contact', 'feedback', 'request'],
      required: true,
    },
    {
      name: 'message',
      type: 'textarea',
      access: { read: adManagerFieldRead },
      maxLength: 2_000,
      required: true,
    },
    {
      name: 'status',
      type: 'select',
      options: ['new', 'reviewed', 'closed'],
      defaultValue: 'new',
      required: true,
    },
  ],
}

export const CustomerSecurityEvents: CollectionConfig = {
  slug: 'customerSecurityEvents',
  access: { create: deny, delete: deny, read: ownOrSystem('customer'), update: deny },
  admin: { group: ADMIN_GROUPS.operations, hidden: systemAdminHidden },
  fields: [
    {
      name: 'customer',
      type: 'relationship',
      relationTo: 'customers',
      index: true,
      required: true,
    },
    { name: 'event', type: 'text', required: true },
    { name: 'occurredAt', type: 'date', required: true },
    { name: 'safeMetadata', type: 'json' },
  ],
}
